project_id = "sgpefhfmcykwtfqfwzcq"

[functions.merchant-signup]
verify_jwt = false

[functions.admin-confirm-merchant]
verify_jwt = true

[functions.release-escrow]
verify_jwt = true

[functions.admin-setup]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.admin-verify-session]
verify_jwt = false
